name: sell
description: Gestiona tus ventas

# La siguiente línea evita que el paquete se publique accidentalmente en
# pub.dev usando `publicación de flutter pub`. Esto es preferible para paquetes privados.
publish_to: 'none' # Quite esta línea si desea publicar en pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.4+9

environment:
  sdk: '^3.0.0' 

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
 

  # Google
  google_sign_in: ^6.2.1
  # Firebase
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_auth: ^5.1.4
  #firebase_dynamic_links: ^5.4.6
  # Google Pay
  in_app_review: ^2.0.9

  # RevanueCat  
  purchases_flutter: ^7.0.1 # Un complemento de Flutter para la API de compras de RevenueCat.

  # state controller
  get: ^4.6.6 # GetX es una solución potente y extraligera para Flutter. Combina la gestión del estado de alto rendimiento, la inyección inteligente de dependencias y la gestión de rutas de forma rápida y práctica.
  # storage 
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.2
  # app info 
  package_info_plus: ^8.0.1 # Un complemento de Flutter para obtener información sobre el paquete actual, como el nombre, la versión y el número de compilación.
  #animations
  lottie: ^3.1.2

  # others   
  observe_internet_connectivity: ^1.0.2 # Un paquete de Flutter que proporciona un widget de conexión a Internet que se puede usar para verificar la conectividad a Internet
  fast_cached_network_image: ^1.2.9
  cached_network_image: ^3.4.0 # Un paquete de Flutter que proporciona una implementación de red de imágenes que se almacenan en caché.
  image_picker: ^1.1.2  # Un complemento de Flutter para seleccionar imágenes desde el almacenamiento local del dispositivo.
  palette_generator: ^0.3.3+4 # Un paquete de Flutter que genera paletas de colores a partir de imágenes.
  flutter_animate: ^4.5.0 # Un paquete de Flutter que proporciona animaciones de entrada y salida para los widgets de Flutter.
  permission_handler: ^11.3.1 # Un complemento de Flutter para solicitar y administrar permisos en Android y iOS.
  avatar_view: ^1.0.1 # Un widget de vista de avatar que admite imágenes, iconos y texto.
  path: ^1.9.0  # Una completa biblioteca de manipulación de rutas multiplataforma para Dart.
  url_launcher: ^6.3.0  # Un complemento de Flutter para abrir una URL en la plataforma nativa.
  font_awesome_flutter: ^10.7.0 # Un paquete de iconos de Flutter que contiene más de 2.000 iconos de Font Awesome.
  animate_do: ^3.3.1 # Un paquete de animación inspirado en Animate.css , construido usando solo animaciones de Flutter, sin paquetes adicionales.
  intl: ^0.19.0
  textfield_search: ^0.11.1 # FTFS es un paquete de Flutter que usa un TextField Widget para buscar y seleccionar un valor de una lista
  search_page: ^2.3.0
  flutter_launcher_icons: ^0.13.1 #  Una herramienta de línea de comandos que simplifica la tarea de actualizar el icono de inicio de la aplicación Flutter
  flutter_barcode_scanner: ^2.0.0 # Un complemento para las aplicaciones Flutter que agrega compatibilidad con el escaneo de códigos de barras tanto en Android como en iOS.
  audioplayers: ^6.0.0 
  shimmer: ^3.0.0 # Un paquete de Flutter que proporciona un widget de efecto de brillo.
  uuid: ^4.4.2  # Un paquete de Flutter que genera identificadores únicos universales (UUID). 
  file_picker: ^8.0.7 # Un complemento de Flutter para seleccionar archivos desde el almacenamiento local del dispositivo.
  #excel: ^4.0.3
  clipboard: ^0.1.3 # Un paquete de Flutter que proporciona acceso al portapapeles del sistema.
  external_app_launcher: ^4.0.0 #Un complemento de Flutter que te ayuda a abrir otra aplicación desde tu aplicación. El paquete le solicita cuatro parámetros, de los cuales dos son obligatorios.
  #carousel_slider: ^5.0.0 # Un widget deslizante de carrusel
  email_validator: ^3.0.0
  blur: ^4.0.0  # Un paquete de Flutter que proporciona un widget de enfoque de desenfoque.
  #fl_chart: ^0.68.0 # Un paquete de Flutter que proporciona un widget de gráfico de datos.
  flutter_cache: ^0.1.0   
  snapping_sheet: ^3.1.0  # Esta es una hoja inferior con una altura que se puede arrastrar  
  screenshot: ^3.0.0 
  share_plus: ^10.0.0
  pdf: ^3.11.0




flutter_icons:
  android: true
  ios: false
  image_path: "assets/launcher.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # El paquete "flutter_lints" a continuación contiene un conjunto de lints recomendados para
  # fomentar buenas prácticas de codificación. El juego de pelusa proporcionado por el paquete es
  # activado en el archivo `analysis_options.yaml` ubicado en la raíz de su
  # paquete. Consulte ese archivo para obtener información sobre cómo desactivar pelusas específicas.
  # reglas y activación de otras adicionales.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  
      - assets/soundBip.mp3
      - assets/scanbarcode.png
      - assets/productoLogo.png
      - assets/default_image.png
      - assets/catalogue.jpeg
      - assets/catalogue01.jpeg
      - assets/catalogue02.png
      - assets/catalogue03.jpeg
      - assets/sell.jpeg
      - assets/sell01.jpeg
      - assets/sell02.jpeg
      - assets/sell03.jpeg
      - assets/sell04.jpeg
      - assets/sell05.jpeg
      - assets/sell06.jpeg
      - assets/sell07.jpeg
      - assets/transaction.png
      - assets/premium_anim.json 
      - assets/analytics.png
      - assets/stock.jpeg 
      - assets/premium.jpeg 
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
